version: '3.8'
services:
  db:
    restart: always
    image: mysql:latest
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: EternalGaming 
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    
  bot:
    restart: always
    build: .
    environment:
      DB_ADDRESS: db
    depends_on:
      - db
volumes:
  db-data: